<?php
// config/countries.php

return [
    'list' => [
        ['code' => '+93', 'emoji' => '🇦🇫', 'name' => 'Afghanistan'],
        ['code' => '+355', 'emoji' => '🇦🇱', 'name' => 'Albania'],
        ['code' => '+213', 'emoji' => '🇩🇿', 'name' => 'Algeria'],
        ['code' => '+1-684', 'emoji' => '🇦🇸', 'name' => 'American Samoa'],
        ['code' => '+376', 'emoji' => '🇦🇩', 'name' => 'Andorra'],
        ['code' => '+244', 'emoji' => '🇦🇴', 'name' => 'Angola'],
        ['code' => '+1-264', 'emoji' => '🇦🇮', 'name' => 'Anguilla'],
        ['code' => '+672', 'emoji' => '🇦🇶', 'name' => 'Antarctica'],
        ['code' => '+1-268', 'emoji' => '🇦🇬', 'name' => 'Antigua and Barbuda'],
        ['code' => '+54', 'emoji' => '🇦🇷', 'name' => 'Argentina'],
        ['code' => '+374', 'emoji' => '🇦🇲', 'name' => 'Armenia'],
        ['code' => '+297', 'emoji' => '🇦🇼', 'name' => 'Aruba'],
        ['code' => '+61', 'emoji' => '🇦🇺', 'name' => 'Australia'],
        ['code' => '+43', 'emoji' => '🇦🇹', 'name' => 'Austria'],
        ['code' => '+994', 'emoji' => '🇦🇿', 'name' => 'Azerbaijan'],
        ['code' => '+1-242', 'emoji' => '🇧🇸', 'name' => 'Bahamas'],
        ['code' => '+973', 'emoji' => '🇧🇭', 'name' => 'Bahrain'],
        ['code' => '+880', 'emoji' => '🇧🇩', 'name' => 'Bangladesh'],
        ['code' => '+1-246', 'emoji' => '🇧🇧', 'name' => 'Barbados'],
        ['code' => '+375', 'emoji' => '🇧🇾', 'name' => 'Belarus'],
        ['code' => '+32', 'emoji' => '🇧🇪', 'name' => 'Belgium'],
        ['code' => '+501', 'emoji' => '🇧🇿', 'name' => 'Belize'],
        ['code' => '+229', 'emoji' => '🇧🇯', 'name' => 'Benin'],
        ['code' => '+1-441', 'emoji' => '🇧🇲', 'name' => 'Bermuda'],
        ['code' => '+975', 'emoji' => '🇧🇹', 'name' => 'Bhutan'],
        ['code' => '+591', 'emoji' => '🇧🇴', 'name' => 'Bolivia'],
        ['code' => '+387', 'emoji' => '🇧🇦', 'name' => 'Bosnia and Herzegovina'],
        ['code' => '+267', 'emoji' => '🇧🇼', 'name' => 'Botswana'],
        ['code' => '+55', 'emoji' => '🇧🇷', 'name' => 'Brazil'],
        ['code' => '+246', 'emoji' => '🇮🇴', 'name' => 'British Indian Ocean Territory'],
        ['code' => '+1-284', 'emoji' => '🇻🇬', 'name' => 'British Virgin Islands'],
        ['code' => '+673', 'emoji' => '🇧🇳', 'name' => 'Brunei'],
        ['code' => '+359', 'emoji' => '🇧🇬', 'name' => 'Bulgaria'],
        ['code' => '+226', 'emoji' => '🇧🇫', 'name' => 'Burkina Faso'],
        ['code' => '+257', 'emoji' => '🇧🇮', 'name' => 'Burundi'],
        ['code' => '+855', 'emoji' => '🇰🇭', 'name' => 'Cambodia'],
        ['code' => '+237', 'emoji' => '🇨🇲', 'name' => 'Cameroon'],
        ['code' => '+1', 'emoji' => '🇨🇦', 'name' => 'Canada'],
        ['code' => '+238', 'emoji' => '🇨🇻', 'name' => 'Cape Verde'],
        ['code' => '+1-345', 'emoji' => '🇰🇾', 'name' => 'Cayman Islands'],
        ['code' => '+236', 'emoji' => '🇨🇫', 'name' => 'Central African Republic'],
        ['code' => '+235', 'emoji' => '🇹🇩', 'name' => 'Chad'],
        ['code' => '+56', 'emoji' => '🇨🇱', 'name' => 'Chile'],
        ['code' => '+86', 'emoji' => '🇨🇳', 'name' => 'China'],
        ['code' => '+61', 'emoji' => '🇨🇽', 'name' => 'Christmas Island'],
        ['code' => '+61', 'emoji' => '🇨🇨', 'name' => 'Cocos (Keeling) Islands'],
        ['code' => '+57', 'emoji' => '🇨🇴', 'name' => 'Colombia'],
        ['code' => '+269', 'emoji' => '🇰🇲', 'name' => 'Comoros'],
        ['code' => '+242', 'emoji' => '🇨🇬', 'name' => 'Congo (Brazzaville)'],
        ['code' => '+243', 'emoji' => '🇨🇩', 'name' => 'Congo (Kinshasa)'],
        ['code' => '+682', 'emoji' => '🇨🇰', 'name' => 'Cook Islands'],
        ['code' => '+506', 'emoji' => '🇨🇷', 'name' => 'Costa Rica'],
        ['code' => "+225", 'emoji' => '🇨🇮', 'name' => "Côte d'Ivoire"],
        ['code' => '+385', 'emoji' => '🇭🇷', 'name' => 'Croatia'],
        ['code' => '+53', 'emoji' => '🇨🇺', 'name' => 'Cuba'],
        ['code' => '+599', 'emoji' => '🇨🇼', 'name' => 'Curaçao'],
        ['code' => '+357', 'emoji' => '🇨🇾', 'name' => 'Cyprus'],
        ['code' => '+420', 'emoji' => '🇨🇿', 'name' => 'Czech Republic'],
        ['code' => '+45', 'emoji' => '🇩🇰', 'name' => 'Denmark'],
        ['code' => '+253', 'emoji' => '🇩🇯', 'name' => 'Djibouti'],
        ['code' => '+1-767', 'emoji' => '🇩🇲', 'name' => 'Dominica'],
        ['code' => '+1-809', 'emoji' => '🇩🇴', 'name' => 'Dominican Republic'],
        ['code' => '+593', 'emoji' => '🇪🇨', 'name' => 'Ecuador'],
        ['code' => '+20', 'emoji' => '🇪🇬', 'name' => 'Egypt'],
        ['code' => '+503', 'emoji' => '🇸🇻', 'name' => 'El Salvador'],
        ['code' => '+240', 'emoji' => '🇬🇶', 'name' => 'Equatorial Guinea'],
        ['code' => '+291', 'emoji' => '🇪🇷', 'name' => 'Eritrea'],
        ['code' => '+372', 'emoji' => '🇪🇪', 'name' => 'Estonia'],
        ['code' => '+251', 'emoji' => '🇪🇹', 'name' => 'Ethiopia'],
        ['code' => '+500', 'emoji' => '🇫🇰', 'name' => 'Falkland Islands'],
        ['code' => '+298', 'emoji' => '🇫🇴', 'name' => 'Faroe Islands'],
        ['code' => '+679', 'emoji' => '🇫🇯', 'name' => 'Fiji'],
        ['code' => '+358', 'emoji' => '🇫🇮', 'name' => 'Finland'],
        ['code' => '+33', 'emoji' => '🇫🇷', 'name' => 'France'],
        ['code' => '+594', 'emoji' => '🇬🇫', 'name' => 'French Guiana'],
        ['code' => '+689', 'emoji' => '🇵🇫', 'name' => 'French Polynesia'],
        ['code' => '+241', 'emoji' => '🇬🇦', 'name' => 'Gabon'],
        ['code' => '+220', 'emoji' => '🇬🇲', 'name' => 'Gambia'],
        ['code' => '+995', 'emoji' => '🇬🇪', 'name' => 'Georgia'],
        ['code' => '+49', 'emoji' => '🇩🇪', 'name' => 'Germany'],
        ['code' => '+233', 'emoji' => '🇬🇭', 'name' => 'Ghana'],
        ['code' => '+350', 'emoji' => '🇬🇮', 'name' => 'Gibraltar'],
        ['code' => '+30', 'emoji' => '🇬🇷', 'name' => 'Greece'],
        ['code' => '+299', 'emoji' => '🇬🇱', 'name' => 'Greenland'],
        ['code' => '+1-473', 'emoji' => '🇬🇩', 'name' => 'Grenada'],
        ['code' => '+590', 'emoji' => '🇬🇵', 'name' => 'Guadeloupe'],
        ['code' => '+1-671', 'emoji' => '🇬🇺', 'name' => 'Guam'],
        ['code' => '+502', 'emoji' => '🇬🇹', 'name' => 'Guatemala'],
        ['code' => '+44-1481', 'emoji' => '🇬🇬', 'name' => 'Guernsey'],
        ['code' => '+224', 'emoji' => '🇬🇳', 'name' => 'Guinea'],
        ['code' => '+245', 'emoji' => '🇬🇼', 'name' => 'Guinea-Bissau'],
        ['code' => '+592', 'emoji' => '🇬🇾', 'name' => 'Guyana'],
        ['code' => '+509', 'emoji' => '🇭🇹', 'name' => 'Haiti'],
        ['code' => '+504', 'emoji' => '🇭🇳', 'name' => 'Honduras'],
        ['code' => '+852', 'emoji' => '🇭🇰', 'name' => 'Hong Kong'],
        ['code' => '+36', 'emoji' => '🇭🇺', 'name' => 'Hungary'],
        ['code' => '+354', 'emoji' => '🇮🇸', 'name' => 'Iceland'],
        ['code' => '+91', 'emoji' => '🇮🇳', 'name' => 'India'],
        ['code' => '+62', 'emoji' => '🇮🇩', 'name' => 'Indonesia'],
        ['code' => '+98', 'emoji' => '🇮🇷', 'name' => 'Iran'],
        ['code' => '+964', 'emoji' => '🇮🇶', 'name' => 'Iraq'],
        ['code' => '+353', 'emoji' => '🇮🇪', 'name' => 'Ireland'],
        ['code' => '+44-1624', 'emoji' => '🇮🇲', 'name' => 'Isle of Man'],
        ['code' => '+972', 'emoji' => '🇮🇱', 'name' => 'Israel'],
        ['code' => '+39', 'emoji' => '🇮🇹', 'name' => 'Italy'],
        ['code' => '+1-876', 'emoji' => '🇯🇲', 'name' => 'Jamaica'],
        ['code' => '+81', 'emoji' => '🇯🇵', 'name' => 'Japan'],
        ['code' => '+44-1534', 'emoji' => '🇯🇪', 'name' => 'Jersey'],
        ['code' => '+962', 'emoji' => '🇯🇴', 'name' => 'Jordan'],
        ['code' => '+7', 'emoji' => '🇰🇿', 'name' => 'Kazakhstan'],
        ['code' => '+254', 'emoji' => '🇰🇪', 'name' => 'Kenya'],
        ['code' => '+686', 'emoji' => '🇰🇮', 'name' => 'Kiribati'],
        ['code' => '+383', 'emoji' => '🇽🇰', 'name' => 'Kosovo'],
        ['code' => '+965', 'emoji' => '🇰🇼', 'name' => 'Kuwait'],
        ['code' => '+996', 'emoji' => '🇰🇬', 'name' => 'Kyrgyzstan'],
        ['code' => '+856', 'emoji' => '🇱🇦', 'name' => 'Laos'],
        ['code' => '+371', 'emoji' => '🇱🇻', 'name' => 'Latvia'],
        ['code' => '+961', 'emoji' => '🇱🇧', 'name' => 'Lebanon'],
        ['code' => '+266', 'emoji' => '🇱🇸', 'name' => 'Lesotho'],
        ['code' => '+231', 'emoji' => '🇱🇷', 'name' => 'Liberia'],
        ['code' => '+218', 'emoji' => '🇱🇾', 'name' => 'Libya'],
        ['code' => '+423', 'emoji' => '🇱🇮', 'name' => 'Liechtenstein'],
        ['code' => '+370', 'emoji' => '🇱🇹', 'name' => 'Lithuania'],
        ['code' => '+352', 'emoji' => '🇱🇺', 'name' => 'Luxembourg'],
        ['code' => '+853', 'emoji' => '🇲🇴', 'name' => 'Macau'],
        ['code' => '+389', 'emoji' => '🇲🇰', 'name' => 'Macedonia'],
        ['code' => '+261', 'emoji' => '🇲🇬', 'name' => 'Madagascar'],
        ['code' => '+265', 'emoji' => '🇲🇼', 'name' => 'Malawi'],
        ['code' => '+60', 'emoji' => '🇲🇾', 'name' => 'Malaysia'],
        ['code' => '+960', 'emoji' => '🇲🇻', 'name' => 'Maldives'],
        ['code' => '+223', 'emoji' => '🇲🇱', 'name' => 'Mali'],
        ['code' => '+356', 'emoji' => '🇲🇹', 'name' => 'Malta'],
        ['code' => '+692', 'emoji' => '🇲🇭', 'name' => 'Marshall Islands'],
        ['code' => '+596', 'emoji' => '🇲🇶', 'name' => 'Martinique'],
        ['code' => '+222', 'emoji' => '🇲🇷', 'name' => 'Mauritania'],
        ['code' => '+230', 'emoji' => '🇲🇺', 'name' => 'Mauritius'],
        ['code' => '+262', 'emoji' => '🇾🇹', 'name' => 'Mayotte'],
        ['code' => '+52', 'emoji' => '🇲🇽', 'name' => 'Mexico'],
        ['code' => '+691', 'emoji' => '🇫🇲', 'name' => 'Micronesia'],
        ['code' => '+373', 'emoji' => '🇲🇩', 'name' => 'Moldova'],
        ['code' => '+377', 'emoji' => '🇲🇨', 'name' => 'Monaco'],
        ['code' => '+976', 'emoji' => '🇲🇳', 'name' => 'Mongolia'],
        ['code' => '+382', 'emoji' => '🇲🇪', 'name' => 'Montenegro'],
        ['code' => '+1-664', 'emoji' => '🇲🇸', 'name' => 'Montserrat'],
        ['code' => '+212', 'emoji' => '🇲🇦', 'name' => 'Morocco'],
        ['code' => '+258', 'emoji' => '🇲🇿', 'name' => 'Mozambique'],
        ['code' => '+95', 'emoji' => '🇲🇲', 'name' => 'Myanmar'],
        ['code' => '+264', 'emoji' => '🇳🇦', 'name' => 'Namibia'],
        ['code' => '+674', 'emoji' => '🇳🇷', 'name' => 'Nauru'],
        ['code' => '+977', 'emoji' => '🇳🇵', 'name' => 'Nepal'],
        ['code' => '+31', 'emoji' => '🇳🇱', 'name' => 'Netherlands'],
        ['code' => '+599', 'emoji' => '🇧🇶', 'name' => 'Netherlands Antilles'],
        ['code' => '+687', 'emoji' => '🇳🇨', 'name' => 'New Caledonia'],
        ['code' => '+64', 'emoji' => '🇳🇿', 'name' => 'New Zealand'],
        ['code' => '+505', 'emoji' => '🇳🇮', 'name' => 'Nicaragua'],
        ['code' => '+227', 'emoji' => '🇳🇪', 'name' => 'Niger'],
        ['code' => '+234', 'emoji' => '🇳🇬', 'name' => 'Nigeria'],
        ['code' => '+683', 'emoji' => '🇳🇺', 'name' => 'Niue'],
        ['code' => '+672', 'emoji' => '🇳🇫', 'name' => 'Norfolk Island'],
        ['code' => '+850', 'emoji' => '🇰🇵', 'name' => 'North Korea'],
        ['code' => '+1-670', 'emoji' => '🇲🇵', 'name' => 'Northern Mariana Islands'],
        ['code' => '+47', 'emoji' => '🇳🇴', 'name' => 'Norway'],
        ['code' => '+968', 'emoji' => '🇴🇲', 'name' => 'Oman'],
        ['code' => '+92', 'emoji' => '🇵🇰', 'name' => 'Pakistan'],
        ['code' => '+680', 'emoji' => '🇵🇼', 'name' => 'Palau'],
        ['code' => '+970', 'emoji' => '🇵🇸', 'name' => 'Palestine'],
        ['code' => '+507', 'emoji' => '🇵🇦', 'name' => 'Panama'],
        ['code' => '+675', 'emoji' => '🇵🇬', 'name' => 'Papua New Guinea'],
        ['code' => '+595', 'emoji' => '🇵🇾', 'name' => 'Paraguay'],
        ['code' => '+51', 'emoji' => '🇵🇪', 'name' => 'Peru'],
        ['code' => '+63', 'emoji' => '🇵🇭', 'name' => 'Philippines'],
        ['code' => '+48', 'emoji' => '🇵🇱', 'name' => 'Poland'],
        ['code' => '+351', 'emoji' => '🇵🇹', 'name' => 'Portugal'],
        ['code' => '+1-787', 'emoji' => '🇵🇷', 'name' => 'Puerto Rico'],
        ['code' => '+974', 'emoji' => '🇶🇦', 'name' => 'Qatar'],
        ['code' => '+262', 'emoji' => '🇷🇪', 'name' => 'Réunion'],
        ['code' => '+40', 'emoji' => '🇷🇴', 'name' => 'Romania'],
        ['code' => '+7', 'emoji' => '🇷🇺', 'name' => 'Russia'],
        ['code' => '+250', 'emoji' => '🇷🇼', 'name' => 'Rwanda'],
        ['code' => '+590', 'emoji' => '🇧🇱', 'name' => 'Saint Barthélemy'],
        ['code' => '+290', 'emoji' => '🇸🇭', 'name' => 'Saint Helena'],
        ['code' => '+1-869', 'emoji' => '🇰🇳', 'name' => 'Saint Kitts and Nevis'],
        ['code' => '+1-758', 'emoji' => '🇱🇨', 'name' => 'Saint Lucia'],
        ['code' => '+590', 'emoji' => '🇲🇫', 'name' => 'Saint Martin'],
        ['code' => '+508', 'emoji' => '🇵🇲', 'name' => 'Saint Pierre and Miquelon'],
        ['code' => '+1-784', 'emoji' => '🇻🇨', 'name' => 'Saint Vincent and the Grenadines'],
        ['code' => '+685', 'emoji' => '🇼🇸', 'name' => 'Samoa'],
        ['code' => '+378', 'emoji' => '🇸🇲', 'name' => 'San Marino'],
        ['code' => '+239', 'emoji' => '🇸🇹', 'name' => 'Sao Tome and Principe'],
        ['code' => '+966', 'emoji' => '🇸🇦', 'name' => 'Saudi Arabia'],
        ['code' => '+221', 'emoji' => '🇸🇳', 'name' => 'Senegal'],
        ['code' => '+381', 'emoji' => '🇷🇸', 'name' => 'Serbia'],
        ['code' => '+248', 'emoji' => '🇸🇨', 'name' => 'Seychelles'],
        ['code' => '+232', 'emoji' => '🇸🇱', 'name' => 'Sierra Leone'],
        ['code' => '+65', 'emoji' => '🇸🇬', 'name' => 'Singapore'],
        ['code' => '+421', 'emoji' => '🇸🇰', 'name' => 'Slovakia'],
        ['code' => '+386', 'emoji' => '🇸🇮', 'name' => 'Slovenia'],
        ['code' => '+677', 'emoji' => '🇸🇧', 'name' => 'Solomon Islands'],
        ['code' => '+252', 'emoji' => '🇸🇴', 'name' => 'Somalia'],
        ['code' => '+27', 'emoji' => '🇿🇦', 'name' => 'South Africa'],
        ['code' => '+82', 'emoji' => '🇰🇷', 'name' => 'South Korea'],
        ['code' => '+211', 'emoji' => '🇸🇸', 'name' => 'South Sudan'],
        ['code' => '+34', 'emoji' => '🇪🇸', 'name' => 'Spain'],
        ['code' => '+94', 'emoji' => '🇱🇰', 'name' => 'Sri Lanka'],
        ['code' => '+249', 'emoji' => '🇸🇩', 'name' => 'Sudan'],
        ['code' => '+597', 'emoji' => '🇸🇷', 'name' => 'Suriname'],
        ['code' => '+47', 'emoji' => '🇸🇯', 'name' => 'Svalbard and Jan Mayen'],
        ['code' => '+268', 'emoji' => '🇸🇿', 'name' => 'Swaziland'],
        ['code' => '+46', 'emoji' => '🇸🇪', 'name' => 'Sweden'],
        ['code' => '+41', 'emoji' => '🇨🇭', 'name' => 'Switzerland'],
        ['code' => '+963', 'emoji' => '🇸🇾', 'name' => 'Syria'],
        ['code' => '+886', 'emoji' => '🇹🇼', 'name' => 'Taiwan'],
        ['code' => '+992', 'emoji' => '🇹🇯', 'name' => 'Tajikistan'],
        ['code' => '+255', 'emoji' => '🇹🇿', 'name' => 'Tanzania'],
        ['code' => '+66', 'emoji' => '🇹🇭', 'name' => 'Thailand'],
        ['code' => '+670', 'emoji' => '🇹🇱', 'name' => 'Timor-Leste'],
        ['code' => '+228', 'emoji' => '🇹🇬', 'name' => 'Togo'],
        ['code' => '+690', 'emoji' => '🇹🇰', 'name' => 'Tokelau'],
        ['code' => '+676', 'emoji' => '🇹🇴', 'name' => 'Tonga'],
        ['code' => '+1-868', 'emoji' => '🇹🇹', 'name' => 'Trinidad and Tobago'],
        ['code' => '+216', 'emoji' => '🇹🇳', 'name' => 'Tunisia'],
        ['code' => '+90', 'emoji' => '🇹🇷', 'name' => 'Turkey'],
        ['code' => '+993', 'emoji' => '🇹🇲', 'name' => 'Turkmenistan'],
        ['code' => '+1-649', 'emoji' => '🇹🇨', 'name' => 'Turks and Caicos Islands'],
        ['code' => '+688', 'emoji' => '🇹🇻', 'name' => 'Tuvalu'],
        ['code' => '+1-340', 'emoji' => '🇻🇮', 'name' => 'U.S. Virgin Islands'],
        ['code' => '+256', 'emoji' => '🇺🇬', 'name' => 'Uganda'],
        ['code' => '+380', 'emoji' => '🇺🇦', 'name' => 'Ukraine'],
        ['code' => '+971', 'emoji' => '🇦🇪', 'name' => 'United Arab Emirates'],
        ['code' => '+44', 'emoji' => '🇬🇧', 'name' => 'United Kingdom'],
        ['code' => '+598', 'emoji' => '🇺🇾', 'name' => 'Uruguay'],
        ['code' => '+998', 'emoji' => '🇺🇿', 'name' => 'Uzbekistan'],
        ['code' => '+678', 'emoji' => '🇻🇺', 'name' => 'Vanuatu'],
        ['code' => '+379', 'emoji' => '🇻🇦', 'name' => 'Vatican'],
        ['code' => '+58', 'emoji' => '🇻🇪', 'name' => 'Venezuela'],
        ['code' => '+84', 'emoji' => '🇻🇳', 'name' => 'Vietnam'],
        ['code' => '+681', 'emoji' => '🇼🇫', 'name' => 'Wallis and Futuna'],
        ['code' => '+212', 'emoji' => '🇪🇭', 'name' => 'Western Sahara'],
        ['code' => '+967', 'emoji' => '🇾🇪', 'name' => 'Yemen'],
        ['code' => '+260', 'emoji' => '🇿🇲', 'name' => 'Zambia'],
        ['code' => '+263', 'emoji' => '🇿🇼', 'name' => 'Zimbabwe'],
    ],
];